# Generated by Django 3.2.7 on 2021-10-01 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import systeme_recom.current_user


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('systeme_recom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='user',
            field=models.ForeignKey(default=systeme_recom.current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
