# Generated by Django 3.2.7 on 2021-10-20 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systeme_recom', '0002_alter_culture_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
